# Generated by Django 3.1 on 2020-08-23 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='description',
        ),
    ]
