# Generated by Django 3.1 on 2020-09-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0003_auto_20200831_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('caste', models.CharField(max_length=200)),
                ('subcaste', models.CharField(max_length=200)),
                ('gothra', models.CharField(max_length=200)),
                ('nakshatra', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('reason', models.CharField(choices=[('ADN', 'Annadaana nidhi'), ('BLD', 'Building fund'), ('OTH', 'Others')], max_length=254)),
                ('date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='caste',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='booking',
            name='gothra',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='booking',
            name='nakshatra',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='booking',
            name='subcaste',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='booking',
            name='contact',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
