# Generated by Django 3.1 on 2020-09-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0004_auto_20200910_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='donations',
            name='amount',
            field=models.CharField(default='', max_length=254),
        ),
    ]
