# Generated by Django 3.1 on 2020-09-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0005_donations_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('caste', models.CharField(max_length=200)),
                ('subcaste', models.CharField(max_length=200)),
                ('gothra', models.CharField(max_length=200)),
                ('nakshatra', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('reason', models.CharField(choices=[('Van', 'VAN'), ('OBSM', 'Obs. materials'), ('Purohit', 'Purohit charges'), ('OTH', 'Others')], max_length=254)),
                ('date', models.DateField(auto_now=True)),
                ('amount', models.CharField(default='', max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='donations',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='donations',
            name='reason',
            field=models.CharField(choices=[('PUD', 'Puduvattu'), ('ADN', 'Annadaana nidhi'), ('BLD', 'Building fund'), ('OTH', 'Others')], max_length=254),
        ),
    ]
