# Generated by Django 3.1 on 2021-03-27 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0006_auto_20200910_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='donations',
            name='reason',
            field=models.CharField(choices=[('Puduvattu', 'Puduvattu'), ('Annadaana nidhi', 'Annadaana nidhi'), ('BLD', 'Building fund'), ('OTH', 'Others')], max_length=254),
        ),
    ]
