# Generated by Django 3.1 on 2021-03-27 12:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0007_auto_20210327_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booked_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
