# Generated by Django 3.1 on 2021-04-05 16:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0008_booking_booked_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(choices=[('OBSM', 'Obs. materials'), ('OTH', 'Others')], max_length=200)),
                ('sub_category', models.CharField(max_length=500)),
                ('amount', models.CharField(max_length=500)),
                ('booked_on', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='ambulance',
            name='booked_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donations',
            name='booked_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
