# Generated by Django 3.1 on 2021-04-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0009_auto_20210405_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='mode_of_payment',
            field=models.CharField(default='Cash', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expenses',
            name='to',
            field=models.CharField(default='Unknown', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expenses',
            name='amount',
            field=models.CharField(default='Cash', max_length=500),
        ),
    ]
