# Generated by Django 3.1 on 2021-04-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0010_auto_20210405_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenses',
            old_name='Category',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='expenses',
            name='amount',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='mode_of_payment',
            field=models.CharField(default='Cash', max_length=1000),
        ),
    ]
