# Generated by Django 3.1 on 2021-04-05 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0011_auto_20210405_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Booked', 'Booked'), ('Cancelled', 'Cancelled')], default='Booked', max_length=100),
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='reason',
            field=models.CharField(choices=[('Van', 'VAN'), ('OBSM', 'Obs. materials'), ('OTH', 'Others')], max_length=254),
        ),
        migrations.AlterField(
            model_name='donations',
            name='reason',
            field=models.CharField(choices=[('Puduvattu', 'Puduvattu'), ('Annadaana nidhi', 'Annadaana nidhi'), ('BLD', 'Building fund'), ('OTH', 'Others'), ('Aparakarma nidhi', 'Aparakarma nidhi')], max_length=254),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='category',
            field=models.CharField(choices=[('Obs. materials', 'Obs. materials'), ('Others', 'Others')], max_length=200),
        ),
    ]
